"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vue_1 = require("vue");
var App_vue_1 = require("@/App.vue");
require("@/style.css");
var providers_1 = require("@/app/providers");
var ui_store_1 = require("@/stores/ui.store");
var app = (0, vue_1.createApp)(App_vue_1.default);
(0, providers_1.registerProviders)(app);
(0, ui_store_1.useUIStore)().initializeTheme();
app.mount('#app');
